name = "ShowTime"
uuid = "8e9fbd02-e9ca-41d0-a20a-ab3a47c5ec0a"
authors = ["Sam Buercklin <sam.buercklin@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
Aqua = "0.8"
AutoHashEquals = "2"
MacroTools = "0.5"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
